#!/bin/bash
echo "Bash betiği örnek 2"
echo ""

echo "Döngü başlasın..."
echo "Başlangıç: `date`"
sayac=0
until [ "$sayac" -eq "15" ]
do
        tarih=`date '+%u' --date="$sayac days"`
        if [ "$tarih" -eq "6" ] || [ "$tarih" -eq "7" ]; then
                echo `date '+%A %D' --date="$sayac days"` " - uyy tatiiiiil"
        else
                echo `date '+%A %D' --date="$sayac days"`
        fi
        ((sayac=sayac+1))
done
echo "bitti"
